# Generated by Django 4.2.7 on 2023-11-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Antiparacitate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("dia_aplicacion", models.DateField()),
                ("proxima_fecha_1", models.DateField()),
                ("proxima_fecha_2", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("specie", models.CharField(max_length=50)),
                ("birth_date", models.DateField()),
                ("breed", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Vacune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("dia_aplicacion", models.DateField()),
                ("proxima_fecha", models.DateField()),
            ],
        ),
    ]
