# Generated by Django 4.2.7 on 2023-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_mascotas", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Antiparacitate",
            new_name="Antiparasitic",
        ),
        migrations.RenameField(
            model_name="antiparasitic",
            old_name="proxima_fecha_1",
            new_name="proxima_fecha",
        ),
        migrations.RenameField(
            model_name="antiparasitic",
            old_name="proxima_fecha_2",
            new_name="refuerzo",
        ),
        migrations.AddField(
            model_name="pet",
            name="antiparasitic",
            field=models.ManyToManyField(
                blank=True, related_name="pets", to="gestion_mascotas.antiparasitic"
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="vacunes",
            field=models.ManyToManyField(
                blank=True, related_name="pets", to="gestion_mascotas.vacune"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
